INSERT INTO `zeitschriften` (`id`, `name`, `shortcut`) VALUES
(1, 'Agricultural Meteorology', 'AgricMet'),
(2, 'Annalen der Meteorologie', 'Annalen'),
(3, 'Annual Review of Fluid Mechanics', 'AnnRevFlMech'),
(4, 'Applied Optics', 'ApplOpt'),
(5, 'Archiv für Meteorologie, Geophysik und Bioklimatologie', 'ArchMetGeophBiokl'),
(6, 'Atmosfera', 'Atmosfera'),
(7, 'Atmosphere-Ocean', 'AtmOcean'),
(8, 'Atmospheric Environment', 'AtmEnv'),
(9, 'Australian Meteorological Magazine', 'AustMetMag'),
(10, 'Beiträge zur Physik der Atmosphäre', 'BeitrPhysAtm'),
(11, 'Boundary Layer Meteorology', 'BLMet'),
(12, 'Bulletin of the American Meteorolgical Society', 'BullAMS'),
(13, 'Climate Dynamics', 'ClimDyn'),
(14, 'Climatic Change', 'ClimChange'),
(15, 'Deep Sea Research', 'DeepSeaRes'),
(16, 'Deutsche Hydrographische Zeitschrift', 'DtschHydrogrZ'),
(17, 'Dynamics of Atmospheres and Oceans', 'DynAtmOceans'),
(18, 'Eiszeitalter und Gegenwart', 'EiszeitGegenwart'),
(19, 'EOS', 'EOS'),
(20, 'Erdkunde', 'Erdkunde'),
(21, 'Geofisica Pura e Applicata ', 'Geofisica'),
(22, 'Geophysical and Astrophysical Fluid Dynamics', 'GeophAstrophFlDyn'),
(23, 'Geophysical Research Letters', 'GeophysResLet'),
(24, 'Die Geowissenschaften', 'Geowissenschaften'),
(25, 'International Journal of Biometeorology', 'IntJBiomet'),
(26, 'International Journal of Climatology', 'IntJClim'),
(27, 'Izvestiya - Atmospheric and Oceanic Physics', 'Izvestiya'),
(28, 'Journal of Applied Meteorology', 'JAM'),
(29, 'Journal of Atmospheric and Oceanic Technology', 'JAtmOceanTechn'),
(30, 'Journal of the Atmospheric Sciences', 'JAS'),
(31, 'Journal of Climate', 'JClim'),
(32, 'Journal of Climate and Applied Meteorology', 'JClimApplMet'),
(33, 'Journal of Climatology', 'JClimatol'),
(34, 'Journal of Fluid Mechanics', 'JFlMech'),
(35, 'Journal of Geophysical Research', 'JGeophysRes'),
(36, 'Journal of Hydrometeorology', 'JHydro'),
(37, 'Journal of Interdisciplinary Cycle Research', 'JInterdisciplCycleRes'),
(38, 'Journal of Marine Research', 'JMarineRes'),
(39, 'Journal of Meteorology', 'JMet'),
(40, 'Journal of the Meteorological Society of Japan', 'JMetSocJap'),
(41, 'Journal of Physical Oceanography', 'JPhysOcean'),
(42, 'MAUSAM', 'Mausam'),
(43, 'Meteor', 'Meteor'),
(44, 'Meteorological Applications', 'MetAppl'),
(45, 'Meteorological Magazine', 'MetMag'),
(46, 'Meteorologische Rundschau', 'MetRdsch'),
(47, 'Meteorologische Zeitschrift', 'MetZ'),
(48, 'Meteorology and Atmospheric Physics', 'MetAtmPhys'),
(49, 'Monthly Weather Review', 'MWR'),
(50, 'Nature', 'Nature'),
(51, 'Oceanologica Acta', 'OceanActa'),
(52, 'PALAEO-Geography, -Climatology, -Ecology', 'Pgeoclimecol'),
(53, 'Papers in Meteorology and Geophysics', 'PapMetGeophys'),
(54, 'Pure and Applied Geophysics', 'PAGEOPH'),
(55, 'Quarterly Journal of the Royal Meteorological Society', 'QJRMS'),
(56, 'Quaternary Research', 'QuaternRes'),
(57, 'Reviews of Geophysics', 'RevGeophys'),
(58, 'Science', 'Science'),
(59, 'Tellus', 'Tellus'),
(60, 'Theoretical and Applied Climatology', 'TheorApplClim'),
(61, 'Umschau', 'Umschau'),
(62, 'Water Resources Research', 'WaterResourRes'),
(63, 'Weather', 'Weather'),
(64, 'Weather and Forecasting', 'WeaForec'),
(65, 'Weatherwise', 'Weatherwise'),
(66, 'Das Wetter', 'DasWetter'),
(67, 'Wetter und Leben', 'WetterLeben'),
(68, 'WMO Bulletin', 'WMOBull'),
(69, 'Zeitschrift für Geophysik', 'ZfGeophys'),
(70, 'Zeitschrift für Meteorologie', 'ZfMet'),
(71, 'Journal of Applied Meteorology and Climatology', 'JAMC'),
(72, 'Atmospheric Research', 'AtmosRes'),
(73, 'Australian Meteorological and Oceanographic Journal', 'AustMetOceanJ'),
(74, 'Weather, climate and society', 'WCAS'),
(75, 'Antarctic research series', 'Antarct. Res. Ser.');








